#!/bin/bash

mkdir ./include

git clone https://github.com/LouisRoss/spiking-model-core.git
cp spiking-model-core/include/* spiking-model-gpu/include
cp -R spiking-model-core/include/Initializers spiking-model-gpu/include/
cp -R spiking-model-core/include/SensorInputs spiking-model-gpu/include/
cp -R spiking-model-core/config spiking-model-gpu/
cp -R spiking-model-core/ui spiking-model-gpu/
rm -rf spiking-model-core/*
rm -rf spiking-model-core/\.*
rmdir spiking-model-core

git clone https://github.com/nlohmann/json.git
cp -R json/include/nlohmann include/nlohmann
rm -rf json/*
rm -rf json/\.*
rmdir json

git clone https://github.com/BlueBrain/HighFive.git
cp -r HighFive/include/* ./include
rm -rf HighFive/*
rm -rf HighFive/\.*
rmdir HighFive

git clone https://github.com/vincentlaucsb/csv-parser.git
mkdir ./include/csv-parser
cp -r csv-parser/single_include/* ./include/csv-parser
rm -rf csv-parser/*
rm -rf csv-parser/\.*
rmdir csv-parser
